# Generated by Django 4.1.5 on 2023-01-16 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divulgar', '0002_pet_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='slug',
            field=models.SlugField(help_text="Para URL's", max_length=64, unique=True),
        ),
    ]
